on:
  push:
    branches:
      - main

name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get Lastest code
      uses: actions/checkout@v2.3.2

    - name: Sync file
      uses: SamKirkLand/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.samkirland.com
        username: myFtpUser
        password: ${{secrets.ftp_passowed}}
